"""Python mirror of the Prolog validator.

Reads logs/vocabulary.json (generated by Prolog) and scans a given text
for incompatibility trigger patterns. Same semantics as the Prolog
validator: case-insensitive substring match.
"""
from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import List


@dataclass(frozen=True)
class Violation:
    term: str
    rule: str
    trigger: str
    correction: str

    def as_dict(self) -> dict:
        return {
            "term": self.term,
            "rule": self.rule,
            "trigger": self.trigger,
            "correction": self.correction,
        }


def load_vocabulary(path: Path) -> list[dict]:
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def validate(text: str, vocabulary: list[dict]) -> List[Violation]:
    """Return a list of Violation for every (term, incompat, trigger) match."""
    haystack = text.lower()
    hits: list[Violation] = []
    for term in vocabulary:
        for incompat in term.get("incompatibilities", []):
            for trigger in incompat.get("triggers", []):
                if trigger.lower() in haystack:
                    hits.append(
                        Violation(
                            term=term["name"],
                            rule=incompat["rule"],
                            trigger=trigger,
                            correction=incompat["correction"],
                        )
                    )
    return hits


def strip_thinking(text: str) -> tuple[str, str]:
    """DeepSeek-R1 emits <think>...</think> scratchpads. Separate them from the final answer."""
    start_tag = "<think>"
    end_tag = "</think>"
    if start_tag in text and end_tag in text:
        start = text.index(start_tag) + len(start_tag)
        end = text.index(end_tag)
        thinking = text[start:end].strip()
        answer = (text[:text.index(start_tag)] + text[end + len(end_tag):]).strip()
        return answer, thinking
    return text.strip(), ""
