#!/usr/bin/env bash
# Apply the N101 LQL patch to the gemma-2b.vindex.
# Assumes vindex already built at n101_bot/gemma-2b.vindex
# Assumes logs/vocabulary.lql generated by bridge.prepare.
#
# Usage:
#   scripts/apply_patch.sh
#
# Result: logs/n101-vocabulary.vlp (patch file), vindex modified with overlay.

set -euo pipefail

ROOT="/Users/tio/Documents/GitHub/Prolog"
LARQL="$ROOT/larql/target/release/larql"
VINDEX="${VINDEX:-$ROOT/n101_bot/llama32-1b.vindex}"
LQL_SCRIPT="$ROOT/n101_bot/logs/vocabulary.lql"

if [ ! -x "$LARQL" ]; then
    echo "larql binary not found" >&2; exit 1
fi
if [ ! -d "$VINDEX" ]; then
    echo "vindex not found at $VINDEX — run scripts/build_vindex.sh first" >&2; exit 1
fi
if [ ! -f "$LQL_SCRIPT" ]; then
    echo "LQL script not found — run bridge.prepare first" >&2; exit 1
fi

echo "applying LQL patch to vindex"
echo "vindex:  $VINDEX"
echo "script:  $LQL_SCRIPT"
echo

# Prepend USE statement so the script runs against our vindex.
TMP="$(mktemp /tmp/n101-apply.XXXXXX.lql)"
{
    printf 'USE "%s";\n' "$VINDEX"
    cat "$LQL_SCRIPT"
} > "$TMP"

echo "(combined LQL: $TMP)"
"$LARQL" lql "$(cat "$TMP")"

rm -f "$TMP"
echo
echo "patch applied. patch file: $ROOT/n101_bot/logs/n101-vocabulary.vlp"
