% docs/analysis/elaborations.pl
% Generated by strategies/meta/automaton_analyzer.pl
% Generated at: 2026-04-18T13:25:01-0400

:- module(elaborations_output, []).

%% --- strategy_patterns/2 ---
strategy_patterns('COBO',[pat_predecessor_loop,pat_sub_strategy_invocation]).
strategy_patterns('Chunking',[pat_base_decomposition,pat_predecessor_loop,pat_sub_strategy_invocation,pat_successor_loop,pat_target_base_adjustment]).
strategy_patterns('RMB',[pat_base_decomposition,pat_error_branch,pat_predecessor_loop,pat_successor_loop,pat_target_base_adjustment]).
strategy_patterns('Rounding',[pat_base_decomposition,pat_predecessor_loop,pat_sub_strategy_invocation,pat_successor_loop,pat_target_base_adjustment]).
strategy_patterns('COBO (Missing Addend)',[pat_accumulator_addition,pat_error_branch,pat_sub_strategy_invocation,pat_successor_loop]).
strategy_patterns('CBBO (Take Away)',[pat_base_decomposition,pat_error_branch,pat_predecessor_loop]).
strategy_patterns('Decomposition',[pat_predecessor_loop]).
strategy_patterns('Sub Rounding',[pat_accumulator_addition,pat_base_decomposition,pat_error_branch,pat_predecessor_loop]).
strategy_patterns('Sliding',[pat_base_decomposition,pat_error_branch,pat_predecessor_loop,pat_sub_strategy_invocation,pat_successor_loop,pat_target_base_adjustment]).
strategy_patterns('Chunking A',[pat_error_branch,pat_leading_chunk_extraction,pat_predecessor_loop]).
strategy_patterns('Chunking B',[pat_error_branch,pat_successor_loop]).
strategy_patterns('Chunking C',[pat_error_branch,pat_leading_chunk_extraction,pat_predecessor_loop,pat_sub_strategy_invocation]).
strategy_patterns('C2C',[pat_successor_loop]).
strategy_patterns('CBO',[pat_list_redistribution,pat_predecessor_loop,pat_successor_loop]).
strategy_patterns('Commutative Reasoning',[pat_predecessor_loop]).
strategy_patterns('DR',[pat_base_decomposition,pat_partial_product_accumulation,pat_predecessor_loop]).
strategy_patterns('CBO (Division)',[pat_accumulator_addition,pat_base_decomposition,pat_error_branch]).
strategy_patterns('Dealing by Ones',[pat_base_decomposition,pat_list_redistribution,pat_predecessor_loop]).
strategy_patterns('IDP',[pat_error_branch,pat_fact_lookup,pat_predecessor_loop]).
strategy_patterns('UCR',[pat_accumulator_addition,pat_error_branch]).

%% --- unclassified/2 ---
% (none)

%% --- uncovered_module/1 ---
uncovered_module('strategies/math/counting2.pl').
uncovered_module('strategies/math/counting_on_back.pl').
uncovered_module('strategies/math/fraction_semantics.pl').
uncovered_module('strategies/math/jason.pl').
uncovered_module('strategies/math/jason_fsm.pl').
uncovered_module('strategies/math/sar_add_counting_on.pl').
uncovered_module('strategies/math/sar_sub_counting_back.pl').

%% --- elaborates/7 ---
%%   elaborates(Base, Elaborated, SharedPatterns, Type, ConfidenceMax, ConfidenceJaccard, DirectionAsymmetry).
elaborates('COBO','Chunking',[pat_predecessor_loop,pat_sub_strategy_invocation],elaboration,0.4,0.4,3).
elaborates('COBO','RMB',[pat_predecessor_loop],elaboration,0.2,0.16666666666666666,3).
elaborates('COBO','Rounding',[pat_predecessor_loop,pat_sub_strategy_invocation],elaboration,0.4,0.4,3).
elaborates('COBO','COBO (Missing Addend)',[pat_sub_strategy_invocation],elaboration,0.25,0.2,2).
elaborates('Decomposition','COBO',[pat_predecessor_loop],elaboration,0.5,0.5,1).
elaborates('COBO','Sub Rounding',[pat_predecessor_loop],elaboration,0.25,0.2,2).
elaborates('COBO','Sliding',[pat_predecessor_loop,pat_sub_strategy_invocation],elaboration,0.3333333333333333,0.3333333333333333,4).
elaborates('COBO','Chunking A',[pat_predecessor_loop],elaboration,0.3333333333333333,0.25,1).
elaborates('COBO','Chunking C',[pat_predecessor_loop,pat_sub_strategy_invocation],elaboration,0.5,0.5,2).
elaborates('Commutative Reasoning','COBO',[pat_predecessor_loop],elaboration,0.5,0.5,1).
elaborates('COBO','DR',[pat_predecessor_loop],elaboration,0.3333333333333333,0.25,1).
elaborates('COBO','Dealing by Ones',[pat_predecessor_loop],elaboration,0.3333333333333333,0.25,1).
elaborates('COBO','IDP',[pat_predecessor_loop],elaboration,0.3333333333333333,0.25,1).
elaborates('Chunking','RMB',[pat_base_decomposition,pat_predecessor_loop,pat_successor_loop,pat_target_base_adjustment],peer,0.8,0.6666666666666666,0).
elaborates('Chunking','Rounding',[pat_base_decomposition,pat_predecessor_loop,pat_sub_strategy_invocation,pat_successor_loop,pat_target_base_adjustment],peer,1,1,0).
elaborates('Decomposition','Chunking',[pat_predecessor_loop],elaboration,0.2,0.2,4).
elaborates('Sub Rounding','Chunking',[pat_base_decomposition,pat_predecessor_loop],elaboration,0.4,0.2857142857142857,1).
elaborates('Chunking','Sliding',[pat_base_decomposition,pat_predecessor_loop,pat_sub_strategy_invocation,pat_successor_loop,pat_target_base_adjustment],elaboration,0.8333333333333334,0.8333333333333334,1).
elaborates('Chunking A','Chunking',[pat_predecessor_loop],elaboration,0.2,0.14285714285714285,2).
elaborates('Chunking B','Chunking',[pat_successor_loop],elaboration,0.2,0.16666666666666666,3).
elaborates('Chunking C','Chunking',[pat_predecessor_loop,pat_sub_strategy_invocation],elaboration,0.4,0.2857142857142857,1).
elaborates('Commutative Reasoning','Chunking',[pat_predecessor_loop],elaboration,0.2,0.2,4).
elaborates('DR','Chunking',[pat_base_decomposition,pat_predecessor_loop],elaboration,0.4,0.3333333333333333,2).
elaborates('Dealing by Ones','Chunking',[pat_base_decomposition,pat_predecessor_loop],elaboration,0.4,0.3333333333333333,2).
elaborates('IDP','Chunking',[pat_predecessor_loop],elaboration,0.2,0.14285714285714285,2).
elaborates('RMB','Rounding',[pat_base_decomposition,pat_predecessor_loop,pat_successor_loop,pat_target_base_adjustment],peer,0.8,0.6666666666666666,0).
elaborates('Sub Rounding','RMB',[pat_base_decomposition,pat_error_branch,pat_predecessor_loop],elaboration,0.6,0.5,1).
elaborates('RMB','Sliding',[pat_base_decomposition,pat_error_branch,pat_predecessor_loop,pat_successor_loop,pat_target_base_adjustment],elaboration,0.8333333333333334,0.8333333333333334,1).
elaborates('UCR','RMB',[pat_error_branch],elaboration,0.2,0.16666666666666666,3).
elaborates('Sub Rounding','Rounding',[pat_base_decomposition,pat_predecessor_loop],elaboration,0.4,0.2857142857142857,1).
elaborates('Rounding','Sliding',[pat_base_decomposition,pat_predecessor_loop,pat_sub_strategy_invocation,pat_successor_loop,pat_target_base_adjustment],elaboration,0.8333333333333334,0.8333333333333334,1).
elaborates('COBO (Missing Addend)','Chunking',[pat_sub_strategy_invocation,pat_successor_loop],elaboration,0.4,0.2857142857142857,1).
elaborates('COBO (Missing Addend)','RMB',[pat_error_branch,pat_successor_loop],elaboration,0.4,0.2857142857142857,1).
elaborates('COBO (Missing Addend)','Rounding',[pat_sub_strategy_invocation,pat_successor_loop],elaboration,0.4,0.2857142857142857,1).
elaborates('COBO (Missing Addend)','Sub Rounding',[pat_accumulator_addition,pat_error_branch],peer,0.5,0.3333333333333333,0).
elaborates('COBO (Missing Addend)','Sliding',[pat_error_branch,pat_sub_strategy_invocation,pat_successor_loop],elaboration,0.5,0.42857142857142855,2).
elaborates('Chunking A','COBO (Missing Addend)',[pat_error_branch],elaboration,0.25,0.16666666666666666,1).
elaborates('Chunking B','COBO (Missing Addend)',[pat_error_branch,pat_successor_loop],elaboration,0.5,0.5,2).
elaborates('COBO (Missing Addend)','Chunking C',[pat_error_branch,pat_sub_strategy_invocation],peer,0.5,0.3333333333333333,0).
elaborates('IDP','COBO (Missing Addend)',[pat_error_branch],elaboration,0.25,0.16666666666666666,1).
elaborates('UCR','COBO (Missing Addend)',[pat_accumulator_addition,pat_error_branch],elaboration,0.5,0.5,2).
elaborates('COBO','CBBO (Take Away)',[pat_predecessor_loop],elaboration,0.3333333333333333,0.25,1).
elaborates('CBBO (Take Away)','Chunking',[pat_base_decomposition,pat_predecessor_loop],elaboration,0.4,0.3333333333333333,2).
elaborates('CBBO (Take Away)','RMB',[pat_base_decomposition,pat_error_branch,pat_predecessor_loop],elaboration,0.6,0.6,2).
elaborates('CBBO (Take Away)','Rounding',[pat_base_decomposition,pat_predecessor_loop],elaboration,0.4,0.3333333333333333,2).
elaborates('CBBO (Take Away)','COBO (Missing Addend)',[pat_error_branch],elaboration,0.25,0.16666666666666666,1).
elaborates('Decomposition','CBBO (Take Away)',[pat_predecessor_loop],elaboration,0.3333333333333333,0.3333333333333333,2).
elaborates('CBBO (Take Away)','Sub Rounding',[pat_base_decomposition,pat_error_branch,pat_predecessor_loop],elaboration,0.75,0.75,1).
elaborates('CBBO (Take Away)','Sliding',[pat_base_decomposition,pat_error_branch,pat_predecessor_loop],elaboration,0.5,0.5,3).
elaborates('CBBO (Take Away)','Chunking A',[pat_error_branch,pat_predecessor_loop],peer,0.6666666666666666,0.5,0).
elaborates('Chunking B','CBBO (Take Away)',[pat_error_branch],elaboration,0.3333333333333333,0.25,1).
elaborates('CBBO (Take Away)','Chunking C',[pat_error_branch,pat_predecessor_loop],elaboration,0.5,0.4,1).
elaborates('CBBO (Take Away)','CBO',[pat_predecessor_loop],peer,0.3333333333333333,0.2,0).
elaborates('Commutative Reasoning','CBBO (Take Away)',[pat_predecessor_loop],elaboration,0.3333333333333333,0.3333333333333333,2).
elaborates('CBBO (Take Away)','DR',[pat_base_decomposition,pat_predecessor_loop],peer,0.6666666666666666,0.5,0).
elaborates('CBBO (Take Away)','CBO (Division)',[pat_base_decomposition,pat_error_branch],peer,0.6666666666666666,0.5,0).
elaborates('CBBO (Take Away)','Dealing by Ones',[pat_base_decomposition,pat_predecessor_loop],peer,0.6666666666666666,0.5,0).
elaborates('CBBO (Take Away)','IDP',[pat_error_branch,pat_predecessor_loop],peer,0.6666666666666666,0.5,0).
elaborates('UCR','CBBO (Take Away)',[pat_error_branch],elaboration,0.3333333333333333,0.25,1).
elaborates('Decomposition','RMB',[pat_predecessor_loop],elaboration,0.2,0.2,4).
elaborates('Decomposition','Rounding',[pat_predecessor_loop],elaboration,0.2,0.2,4).
elaborates('Decomposition','Sub Rounding',[pat_predecessor_loop],elaboration,0.25,0.25,3).
elaborates('Decomposition','Sliding',[pat_predecessor_loop],elaboration,0.16666666666666666,0.16666666666666666,5).
elaborates('Decomposition','IDP',[pat_predecessor_loop],elaboration,0.3333333333333333,0.3333333333333333,2).
elaborates('UCR','Sub Rounding',[pat_accumulator_addition,pat_error_branch],elaboration,0.5,0.5,2).
elaborates('Sub Rounding','Sliding',[pat_base_decomposition,pat_error_branch,pat_predecessor_loop],elaboration,0.5,0.42857142857142855,2).
elaborates('UCR','Sliding',[pat_error_branch],elaboration,0.16666666666666666,0.14285714285714285,4).
elaborates('Chunking A','RMB',[pat_error_branch,pat_predecessor_loop],elaboration,0.4,0.3333333333333333,2).
elaborates('Chunking A','Rounding',[pat_predecessor_loop],elaboration,0.2,0.14285714285714285,2).
elaborates('Decomposition','Chunking A',[pat_predecessor_loop],elaboration,0.3333333333333333,0.3333333333333333,2).
elaborates('Chunking A','Sub Rounding',[pat_error_branch,pat_predecessor_loop],elaboration,0.5,0.4,1).
elaborates('Chunking A','Sliding',[pat_error_branch,pat_predecessor_loop],elaboration,0.3333333333333333,0.2857142857142857,3).
elaborates('Chunking B','Chunking A',[pat_error_branch],elaboration,0.3333333333333333,0.25,1).
elaborates('Chunking A','Chunking C',[pat_error_branch,pat_leading_chunk_extraction,pat_predecessor_loop],elaboration,0.75,0.75,1).
elaborates('Commutative Reasoning','Chunking A',[pat_predecessor_loop],elaboration,0.3333333333333333,0.3333333333333333,2).
elaborates('Chunking A','DR',[pat_predecessor_loop],peer,0.3333333333333333,0.2,0).
elaborates('Chunking A','Dealing by Ones',[pat_predecessor_loop],peer,0.3333333333333333,0.2,0).
elaborates('Chunking A','IDP',[pat_error_branch,pat_predecessor_loop],peer,0.6666666666666666,0.5,0).
elaborates('UCR','Chunking A',[pat_error_branch],elaboration,0.3333333333333333,0.25,1).
elaborates('Chunking B','RMB',[pat_error_branch,pat_successor_loop],elaboration,0.4,0.4,3).
elaborates('Chunking B','Rounding',[pat_successor_loop],elaboration,0.2,0.16666666666666666,3).
elaborates('Chunking B','Sub Rounding',[pat_error_branch],elaboration,0.25,0.2,2).
elaborates('Chunking B','Sliding',[pat_error_branch,pat_successor_loop],elaboration,0.3333333333333333,0.3333333333333333,4).
elaborates('Chunking B','Chunking C',[pat_error_branch],elaboration,0.25,0.2,2).
elaborates('Chunking B','IDP',[pat_error_branch],elaboration,0.3333333333333333,0.25,1).
elaborates('Chunking B','UCR',[pat_error_branch],peer,0.5,0.3333333333333333,0).
elaborates('Chunking C','RMB',[pat_error_branch,pat_predecessor_loop],elaboration,0.4,0.2857142857142857,1).
elaborates('Chunking C','Rounding',[pat_predecessor_loop,pat_sub_strategy_invocation],elaboration,0.4,0.2857142857142857,1).
elaborates('Decomposition','Chunking C',[pat_predecessor_loop],elaboration,0.25,0.25,3).
elaborates('Chunking C','Sub Rounding',[pat_error_branch,pat_predecessor_loop],peer,0.5,0.3333333333333333,0).
elaborates('Chunking C','Sliding',[pat_error_branch,pat_predecessor_loop,pat_sub_strategy_invocation],elaboration,0.5,0.42857142857142855,2).
elaborates('Commutative Reasoning','Chunking C',[pat_predecessor_loop],elaboration,0.25,0.25,3).
elaborates('DR','Chunking C',[pat_predecessor_loop],elaboration,0.25,0.16666666666666666,1).
elaborates('Dealing by Ones','Chunking C',[pat_predecessor_loop],elaboration,0.25,0.16666666666666666,1).
elaborates('IDP','Chunking C',[pat_error_branch,pat_predecessor_loop],elaboration,0.5,0.4,1).
elaborates('UCR','Chunking C',[pat_error_branch],elaboration,0.25,0.2,2).
elaborates('C2C','Chunking',[pat_successor_loop],elaboration,0.2,0.2,4).
elaborates('C2C','RMB',[pat_successor_loop],elaboration,0.2,0.2,4).
elaborates('C2C','Rounding',[pat_successor_loop],elaboration,0.2,0.2,4).
elaborates('C2C','COBO (Missing Addend)',[pat_successor_loop],elaboration,0.25,0.25,3).
elaborates('C2C','Sliding',[pat_successor_loop],elaboration,0.16666666666666666,0.16666666666666666,5).
elaborates('C2C','Chunking B',[pat_successor_loop],elaboration,0.5,0.5,1).
elaborates('C2C','CBO',[pat_successor_loop],elaboration,0.3333333333333333,0.3333333333333333,2).
elaborates('COBO','CBO',[pat_predecessor_loop],elaboration,0.3333333333333333,0.25,1).
elaborates('CBO','Chunking',[pat_predecessor_loop,pat_successor_loop],elaboration,0.4,0.3333333333333333,2).
elaborates('CBO','RMB',[pat_predecessor_loop,pat_successor_loop],elaboration,0.4,0.3333333333333333,2).
elaborates('CBO','Rounding',[pat_predecessor_loop,pat_successor_loop],elaboration,0.4,0.3333333333333333,2).
elaborates('CBO','COBO (Missing Addend)',[pat_successor_loop],elaboration,0.25,0.16666666666666666,1).
elaborates('Decomposition','CBO',[pat_predecessor_loop],elaboration,0.3333333333333333,0.3333333333333333,2).
elaborates('CBO','Sub Rounding',[pat_predecessor_loop],elaboration,0.25,0.16666666666666666,1).
elaborates('CBO','Sliding',[pat_predecessor_loop,pat_successor_loop],elaboration,0.3333333333333333,0.2857142857142857,3).
elaborates('CBO','Chunking A',[pat_predecessor_loop],peer,0.3333333333333333,0.2,0).
elaborates('Chunking B','CBO',[pat_successor_loop],elaboration,0.3333333333333333,0.25,1).
elaborates('CBO','Chunking C',[pat_predecessor_loop],elaboration,0.25,0.16666666666666666,1).
elaborates('Commutative Reasoning','CBO',[pat_predecessor_loop],elaboration,0.3333333333333333,0.3333333333333333,2).
elaborates('CBO','DR',[pat_predecessor_loop],peer,0.3333333333333333,0.2,0).
elaborates('CBO','Dealing by Ones',[pat_list_redistribution,pat_predecessor_loop],peer,0.6666666666666666,0.5,0).
elaborates('CBO','IDP',[pat_predecessor_loop],peer,0.3333333333333333,0.2,0).
elaborates('Commutative Reasoning','RMB',[pat_predecessor_loop],elaboration,0.2,0.2,4).
elaborates('Commutative Reasoning','Rounding',[pat_predecessor_loop],elaboration,0.2,0.2,4).
elaborates('Commutative Reasoning','Decomposition',[pat_predecessor_loop],peer,1,1,0).
elaborates('Commutative Reasoning','Sub Rounding',[pat_predecessor_loop],elaboration,0.25,0.25,3).
elaborates('Commutative Reasoning','Sliding',[pat_predecessor_loop],elaboration,0.16666666666666666,0.16666666666666666,5).
elaborates('Commutative Reasoning','DR',[pat_predecessor_loop],elaboration,0.3333333333333333,0.3333333333333333,2).
elaborates('Commutative Reasoning','Dealing by Ones',[pat_predecessor_loop],elaboration,0.3333333333333333,0.3333333333333333,2).
elaborates('Commutative Reasoning','IDP',[pat_predecessor_loop],elaboration,0.3333333333333333,0.3333333333333333,2).
elaborates('DR','RMB',[pat_base_decomposition,pat_predecessor_loop],elaboration,0.4,0.3333333333333333,2).
elaborates('DR','Rounding',[pat_base_decomposition,pat_predecessor_loop],elaboration,0.4,0.3333333333333333,2).
elaborates('Decomposition','DR',[pat_predecessor_loop],elaboration,0.3333333333333333,0.3333333333333333,2).
elaborates('DR','Sub Rounding',[pat_base_decomposition,pat_predecessor_loop],elaboration,0.5,0.4,1).
elaborates('DR','Sliding',[pat_base_decomposition,pat_predecessor_loop],elaboration,0.3333333333333333,0.2857142857142857,3).
elaborates('DR','Dealing by Ones',[pat_base_decomposition,pat_predecessor_loop],peer,0.6666666666666666,0.5,0).
elaborates('DR','IDP',[pat_predecessor_loop],peer,0.3333333333333333,0.2,0).
elaborates('CBO (Division)','Chunking',[pat_base_decomposition],elaboration,0.2,0.14285714285714285,2).
elaborates('CBO (Division)','RMB',[pat_base_decomposition,pat_error_branch],elaboration,0.4,0.3333333333333333,2).
elaborates('CBO (Division)','Rounding',[pat_base_decomposition],elaboration,0.2,0.14285714285714285,2).
elaborates('CBO (Division)','COBO (Missing Addend)',[pat_accumulator_addition,pat_error_branch],elaboration,0.5,0.4,1).
elaborates('CBO (Division)','Sub Rounding',[pat_accumulator_addition,pat_base_decomposition,pat_error_branch],elaboration,0.75,0.75,1).
elaborates('CBO (Division)','Sliding',[pat_base_decomposition,pat_error_branch],elaboration,0.3333333333333333,0.2857142857142857,3).
elaborates('CBO (Division)','Chunking A',[pat_error_branch],peer,0.3333333333333333,0.2,0).
elaborates('Chunking B','CBO (Division)',[pat_error_branch],elaboration,0.3333333333333333,0.25,1).
elaborates('CBO (Division)','Chunking C',[pat_error_branch],elaboration,0.25,0.16666666666666666,1).
elaborates('CBO (Division)','DR',[pat_base_decomposition],peer,0.3333333333333333,0.2,0).
elaborates('CBO (Division)','Dealing by Ones',[pat_base_decomposition],peer,0.3333333333333333,0.2,0).
elaborates('CBO (Division)','IDP',[pat_error_branch],peer,0.3333333333333333,0.2,0).
elaborates('UCR','CBO (Division)',[pat_accumulator_addition,pat_error_branch],elaboration,0.6666666666666666,0.6666666666666666,1).
elaborates('Dealing by Ones','RMB',[pat_base_decomposition,pat_predecessor_loop],elaboration,0.4,0.3333333333333333,2).
elaborates('Dealing by Ones','Rounding',[pat_base_decomposition,pat_predecessor_loop],elaboration,0.4,0.3333333333333333,2).
elaborates('Decomposition','Dealing by Ones',[pat_predecessor_loop],elaboration,0.3333333333333333,0.3333333333333333,2).
elaborates('Dealing by Ones','Sub Rounding',[pat_base_decomposition,pat_predecessor_loop],elaboration,0.5,0.4,1).
elaborates('Dealing by Ones','Sliding',[pat_base_decomposition,pat_predecessor_loop],elaboration,0.3333333333333333,0.2857142857142857,3).
elaborates('Dealing by Ones','IDP',[pat_predecessor_loop],peer,0.3333333333333333,0.2,0).
elaborates('IDP','RMB',[pat_error_branch,pat_predecessor_loop],elaboration,0.4,0.3333333333333333,2).
elaborates('IDP','Rounding',[pat_predecessor_loop],elaboration,0.2,0.14285714285714285,2).
elaborates('IDP','Sub Rounding',[pat_error_branch,pat_predecessor_loop],elaboration,0.5,0.4,1).
elaborates('IDP','Sliding',[pat_error_branch,pat_predecessor_loop],elaboration,0.3333333333333333,0.2857142857142857,3).
elaborates('UCR','IDP',[pat_error_branch],elaboration,0.3333333333333333,0.25,1).

%% --- pattern_evidence/3 ---
%%   pattern_evidence(Strategy, Pattern, ev(ClauseHead, Witness)).
pattern_evidence('COBO',pat_predecessor_loop,ev(transition(state(q_add_bases,_75166,1,_75170),state(q_add_bases,_75176,_75178,_75170),_75160),subtract_grounded(_75184,_75186,_75188))).
pattern_evidence('COBO',pat_sub_strategy_invocation,ev(meta,cobo_shape_original)).
pattern_evidence('Chunking',pat_base_decomposition,ev(meta,base_decompose_grounded(_75106,_75108,_75110,_75112))).
pattern_evidence('Chunking',pat_predecessor_loop,ev(transition(state(q_add_ones_chunk,_75048,_75050,1,_75054,_75056,_75058),_75038,state(q_init_ones_chunk,_75064,_75050,_75068,0,0,0),_75042),subtract_grounded(_75078,_75080,_75082))).
pattern_evidence('Chunking',pat_sub_strategy_invocation,ev(meta,k_count_shape)).
pattern_evidence('Chunking',pat_successor_loop,ev(transition(state(q_loop_K,_74948,_74950,_74952,_74954,_74956,_74958),_74938,state(q_loop_K,_74948,_74950,_74952,_74970,_74972,_74958),_74942),(smaller_than(_74984,_74986),successor(_74984,_74992)))).
pattern_evidence('Chunking',pat_target_base_adjustment,ev(meta,calculate_next_base_grounded(_74910,_74912))).
pattern_evidence('RMB',pat_base_decomposition,ev(meta,base_decompose_grounded(_74880,_74882,_74884,_74886))).
pattern_evidence('RMB',pat_error_branch,ev(meta,q_error)).
pattern_evidence('RMB',pat_predecessor_loop,ev(transition(state(q_decompose_B,_74800,_74802,_74804,_74806,_74808,_74810,_74812),_74790,state(q_decompose_B,_74800,_74802,_74822,_74806,_74826,_74810,_74812),_74794),predecessor(_74834,_74836))).
pattern_evidence('RMB',pat_successor_loop,ev(transition(state(q_calc_K,_74716,_74718,_74720,_74722,_74724,_74726,_74728),_74706,state(q_calc_K,_74716,_74718,_74738,_74740,_74724,_74726,_74728),_74710),(smaller_than(_74756,_74758),successor(_74762,_74764)))).
pattern_evidence('RMB',pat_target_base_adjustment,ev(meta,(successor(_74670,_74672),multiply_grounded(_74672,_74678,_74680)))).
pattern_evidence('Rounding',pat_base_decomposition,ev(meta,base_decompose_grounded(_74634,_74636,_74638,_74640))).
pattern_evidence('Rounding',pat_predecessor_loop,ev(transition(state(q_loop_AddBases,_74558,_74560,_74562,_74564,_74566,_74568,_74570,_74572,_74574,_74576,_74578),_74548,state(q_loop_AddBases,_74558,_74560,_74588,_74564,_74566,_74568,_74570,_74598,_74574,_74576,_74578),_74552),predecessor(_74608,_74610))).
pattern_evidence('Rounding',pat_sub_strategy_invocation,ev(meta,cobo_shape_wrapped)).
pattern_evidence('Rounding',pat_successor_loop,ev(transition(state(q_loop_K,_74438,_74440,_74442,_74444,_74446,_74448,_74450,_74452,_74454,_74456,_74458),_74428,state(q_loop_K,_74464,_74466,_74442,_74444,_74446,_74448,_74450,_74452,_74454,_74456,_74458),_74432),(smaller_than(_74494,_74496),successor(_74500,_74502)))).
pattern_evidence('Rounding',pat_target_base_adjustment,ev(meta,(successor(_74392,_74394),multiply_grounded(_74394,_74400,_74402)))).
pattern_evidence('COBO (Missing Addend)',pat_accumulator_addition,ev(transition(state(q_add_bases,_74340,_74342,_74344),_74330,state(q_add_bases,_74350,_74352,_74344),_74334),add_grounded(_74358,_74360,_74362))).
pattern_evidence('COBO (Missing Addend)',pat_error_branch,ev(meta,q_error)).
pattern_evidence('COBO (Missing Addend)',pat_sub_strategy_invocation,ev(meta,cobo_shape_original)).
pattern_evidence('COBO (Missing Addend)',pat_successor_loop,ev(transition(state(q_add_ones,_74232,_74234,_74236),_74222,state(q_add_ones,_74242,_74244,_74236),_74226),(_74232<_74236,successor(_74262,_74264)))).
pattern_evidence('CBBO (Take Away)',pat_base_decomposition,ev(meta,base_decompose_grounded(_74190,_74192,_74194,_74196))).
pattern_evidence('CBBO (Take Away)',pat_error_branch,ev(meta,q_error)).
pattern_evidence('CBBO (Take Away)',pat_predecessor_loop,ev(transition(state(q_sub_bases,_74126,_74128,_74130),_74116,state(q_sub_bases,_74136,_74138,_74130),_74120),predecessor(_74144,_74146))).
pattern_evidence('Decomposition',pat_predecessor_loop,ev(transition(state(q_decompose,_74064,_74066,_74068,_74070),_74054,state(q_sub_ones,_74076,_74078,_74068,_74070),_74058),subtract_grounded(_74064,_74088,_74076))).
pattern_evidence('Sub Rounding',pat_accumulator_addition,ev(transition(state(q_adjust_M,_73982,_73984,_73986,_73988,_73990,_73992,_73994,_73996,_73998),_73972,state(q_init_adjust_S,_73982,_73984,_74008,0,0,_73992,_73994,_73996,_73998),_73976),add_grounded(_74024,_74026,_74028))).
pattern_evidence('Sub Rounding',pat_base_decomposition,ev(meta,base_decompose_grounded(_73940,_73942,_73944,_73946))).
pattern_evidence('Sub Rounding',pat_error_branch,ev(meta,q_error)).
pattern_evidence('Sub Rounding',pat_predecessor_loop,ev(transition(state(q_round_M,_73850,_73852,_73854,_73856,_73858,1,_73862,_73864,_73866),_73840,state(q_round_S,_73872,0,0,0,0,1,_73862,_73886,0),_73844),subtract_grounded(_73892,_73894,_73896))).
pattern_evidence('Sliding',pat_base_decomposition,ev(meta,base_decompose_grounded(_73808,_73810,_73812,_73814))).
pattern_evidence('Sliding',pat_error_branch,ev(meta,q_error)).
pattern_evidence('Sliding',pat_predecessor_loop,ev(final_interpretation(state(q_accept,_73744,1,_73748,_73750,_73752,_73754,_73756),_73738),subtract_grounded(_73760,_73762,_73764))).
pattern_evidence('Sliding',pat_sub_strategy_invocation,ev(meta,k_count_shape)).
pattern_evidence('Sliding',pat_successor_loop,ev(transition(state(q_loop_K,_73644,_73646,_73648,_73650,_73652,_73654,_73656),_73634,state(q_loop_K,_73662,_73646,_73648,_73650,_73670,_73654,_73656),_73638),(smaller_than(_73684,_73686),successor(_73684,_73692)))).
pattern_evidence('Sliding',pat_target_base_adjustment,ev(meta,(successor(_73598,_73600),multiply_grounded(_73600,_73606,_73608)))).
pattern_evidence('Chunking A',pat_error_branch,ev(meta,q_error)).
pattern_evidence('Chunking A',pat_leading_chunk_extraction,ev(meta,leading_digit_chunk(_73544,10,_73548))).
pattern_evidence('Chunking A',pat_predecessor_loop,ev(transition(state(q_subtract_chunk,1,_73500,_73502),_73488,state(q_identify_chunk,_73508,_73510,0),_73492),subtract_grounded(_73516,_73518,_73520))).
pattern_evidence('Chunking B',pat_error_branch,ev(meta,q_error)).
pattern_evidence('Chunking B',pat_successor_loop,ev(transition(state(q_forward_chunking,_73414,_73416,_73418,_73420,_73422,_73424),_73404,_73406,_73408),(_73434>=_73424,successor(_73440,_73442)))).
pattern_evidence('Chunking C',pat_error_branch,ev(meta,q_error)).
pattern_evidence('Chunking C',pat_leading_chunk_extraction,ev(meta,leading_digit_chunk(_73354,10,_73358))).
pattern_evidence('Chunking C',pat_predecessor_loop,ev(transition(state(q_loop_K,_73298,_73300,_73302,_73304,_73306,_73308),_73288,state(q_loop_K,_73298,_73300,_73318,_73304,_73322,_73308),'Counting down to base.'),predecessor(_73328,_73330))).
pattern_evidence('Chunking C',pat_sub_strategy_invocation,ev(meta,k_count_shape)).
pattern_evidence('C2C',pat_successor_loop,ev(transition(state(q_check_G,_73202,_73204,_73206,_73208,_73210),_73192,state(q_count_items,_73202,_73204,_73206,_73208,_73210),_73196),(_73202<_73208,successor(_73240,_73242)))).
pattern_evidence('CBO',pat_list_redistribution,ev(meta,(nth0(_73150,_73152,_73154,_73156),update_list(_73160,_73162,_73164,_73166)))).
pattern_evidence('CBO',pat_predecessor_loop,ev(transition(state(q_loop_transfer,_73098,_73100,_73102),_73088,state(q_loop_transfer,_73108,_73100,_73112),_73092),subtract_grounded(_73116,_73118,_73120))).
pattern_evidence('CBO',pat_successor_loop,ev(transition(state(q_loop_transfer,_73030,_73032,_73034),_73020,state(q_loop_transfer,_73040,_73032,_73044),_73024),(smaller_than(_73034,_73056),successor(_73034,_73044)))).
pattern_evidence('Commutative Reasoning',pat_predecessor_loop,ev(transition(state(q_loop_calc,_72970,_72972,_72974,_72976),state(q_loop_calc,_72970,_72972,_72986,_72988),_72964),predecessor(_72992,_72994))).
pattern_evidence('DR',pat_base_decomposition,ev(meta,base_decompose_grounded(_72930,_72932,_72934,_72936))).
pattern_evidence('DR',pat_partial_product_accumulation,ev(meta,subset_of(ppa_shape))).
pattern_evidence('DR',pat_predecessor_loop,ev(transition(state(q_loop_P1,_72842,_72844,_72846,_72848,_72850,_72852,_72854,_72856),_72832,state(q_loop_P1,_72842,_72844,_72866,_72848,_72850,_72872,_72854,_72856),_72836),predecessor(_72880,_72882))).
pattern_evidence('CBO (Division)',pat_accumulator_addition,ev(transition(state(q_combine_R,_72764,_72766,_72768,_72770,_72772,_72774,_72776,_72778),_72754,state(q_process_R,_72784,_72766,_72768,_72790,_72772,_72774,_72776,_72778),_72758),add_grounded(_72802,_72804,_72806))).
pattern_evidence('CBO (Division)',pat_base_decomposition,ev(meta,base_decompose_grounded(_72722,_72724,_72726,_72728))).
pattern_evidence('CBO (Division)',pat_error_branch,ev(meta,q_error)).
pattern_evidence('Dealing by Ones',pat_base_decomposition,ev(meta,base_decompose_grounded(_72672,_72674,_72676,_72678))).
pattern_evidence('Dealing by Ones',pat_list_redistribution,ev(meta,(twin_nth0_4,[nth0(_72626,_72628,_72630,_72632),nth0(_72642,_72644,_72646,_72648)]))).
pattern_evidence('Dealing by Ones',pat_predecessor_loop,ev(transition(state(q_loop_deal,_72558,_72560,_72562),[_72566,_72572],state(q_loop_deal,_72580,_72582,_72584),_72552),predecessor(_72588,_72590))).
pattern_evidence('IDP',pat_error_branch,ev(meta,q_error)).
pattern_evidence('IDP',pat_fact_lookup,ev(meta,find_best_fact(_72496,_72498,_72500,_72502))).
pattern_evidence('IDP',pat_predecessor_loop,ev(transition(state(q_apply_fact,1,_72440,_72442,_72444,_72446,_72448),_72428,state(q_search_KB,_72454,_72456,0,0,_72446,_72448),_72432),subtract_grounded(_72468,_72470,_72472))).
pattern_evidence('UCR',pat_accumulator_addition,ev(transition(state(q_iterate,_72364,_72366,_72368,_72370),[_72368,_72370],state(q_check,_72388,_72390,_72368,_72370),_72358),add_grounded(_72398,_72400,_72402))).
pattern_evidence('UCR',pat_error_branch,ev(meta,q_error)).
